import jsQR from 'jsqr';
import { Organization } from './api.js';

let offscreenCanvas: HTMLCanvasElement | null = null;
let offscreenCtx: CanvasRenderingContext2D | null = null;

/**
 * Scans the current frame of an HTMLVideoElement for a QR Code.
 */
export function scanQrFromVideo(video: HTMLVideoElement): { data: string; location?: any } | null {
  if (!video || video.readyState < 2 || video.videoWidth === 0) {
    return null;
  }

  const width = video.videoWidth;
  const height = video.videoHeight;

  if (!offscreenCanvas) {
    offscreenCanvas = document.createElement('canvas');
  }

  if (offscreenCanvas.width !== width || offscreenCanvas.height !== height) {
    offscreenCanvas.width = width;
    offscreenCanvas.height = height;
    offscreenCtx = offscreenCanvas.getContext('2d', { willReadFrequently: true });
  }

  if (!offscreenCtx) return null;

  // Draw video frame to offscreen canvas
  offscreenCtx.drawImage(video, 0, 0, width, height);

  try {
    const imageData = offscreenCtx.getImageData(0, 0, width, height);
    const code = jsQR(imageData.data, width, height, {
      inversionAttempts: 'dontInvert',
    });

    if (code && code.data && code.data.trim().length > 0) {
      return {
        data: code.data.trim(),
        location: code.location,
      };
    }
  } catch (err) {
    console.warn('QR decode frame error:', err);
  }

  return null;
}

/**
 * Validates that the scanned QR code matches the Admin-generated Master QR Code for the Organization.
 */
export function validateMasterQr(
  scannedText: string,
  expectedOrg?: Organization | null
): { isValid: boolean; error?: string } {
  if (!scannedText) {
    return { isValid: false, error: 'Empty QR code' };
  }

  // 1. Direct match with Organization's active Master QR Payload
  if (expectedOrg?.masterQrPayload && scannedText === expectedOrg.masterQrPayload) {
    return { isValid: true };
  }

  // 2. Cryptographic signature check: Must start with "QR-ATTEND-V1:"
  if (scannedText.startsWith('QR-ATTEND-V1:')) {
    const parts = scannedText.split(':');
    if (parts.length === 4) {
      return { isValid: true };
    }
  }

  return {
    isValid: false,
    error: 'Scanned QR code is not a valid Organization Master QR code generated by the Admin Panel.',
  };
}
